# Generated by Django 5.2.6 on 2025-09-06 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='criminals/')),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('confidence', models.FloatField(blank=True, default=0.0, help_text='Detection confidence percentage', null=True)),
                ('detection_type', models.CharField(blank=True, choices=[('upload', 'File Upload'), ('real_time_camera', 'Real-time Camera'), ('single_capture', 'Single Capture')], default='upload', max_length=20, null=True)),
                ('is_criminal', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Scan Histories',
                'ordering': ['-date'],
            },
        ),
    ]
